// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcpiUuv0KiEGdhBBBRq1yKXYsrZL5ybv4',
    appId: '1:804708194137:web:7388a0b8f5e7d050b25e48',
    messagingSenderId: '804708194137',
    projectId: 'doova-709a7',
    authDomain: 'doova-709a7.firebaseapp.com',
    databaseURL: 'https://doova-709a7-default-rtdb.firebaseio.com',
    storageBucket: 'doova-709a7.firebasestorage.app',
    measurementId: 'G-155TKN76ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpeddCFNrpKOXJ4nq-0rLSlXR5eMCGr4',
    appId: '1:804708194137:android:41ef41efb6d0f5b5b25e48',
    messagingSenderId: '804708194137',
    projectId: 'doova-709a7',
    databaseURL: 'https://doova-709a7-default-rtdb.firebaseio.com',
    storageBucket: 'doova-709a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA19OmG5Xc5_XIpjmCfvcY9zbUD2UIQPgI',
    appId: '1:804708194137:ios:bdf0b950c52e2c9eb25e48',
    messagingSenderId: '804708194137',
    projectId: 'doova-709a7',
    databaseURL: 'https://doova-709a7-default-rtdb.firebaseio.com',
    storageBucket: 'doova-709a7.firebasestorage.app',
    androidClientId: '804708194137-nc7llsf10r56bmnt8nf8pe2e0e091svr.apps.googleusercontent.com',
    iosClientId: '804708194137-ruk68oslnnasiaq8iphecsa4ajegor6n.apps.googleusercontent.com',
    iosBundleId: 'com.delis.doova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA19OmG5Xc5_XIpjmCfvcY9zbUD2UIQPgI',
    appId: '1:804708194137:ios:172bdfbe9254d711b25e48',
    messagingSenderId: '804708194137',
    projectId: 'doova-709a7',
    databaseURL: 'https://doova-709a7-default-rtdb.firebaseio.com',
    storageBucket: 'doova-709a7.firebasestorage.app',
    androidClientId: '804708194137-nc7llsf10r56bmnt8nf8pe2e0e091svr.apps.googleusercontent.com',
    iosClientId: '804708194137-gv1egls5r4p96v1c4n2s94gle3cfok8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.doova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcpiUuv0KiEGdhBBBRq1yKXYsrZL5ybv4',
    appId: '1:804708194137:web:11b39c4b9172686bb25e48',
    messagingSenderId: '804708194137',
    projectId: 'doova-709a7',
    authDomain: 'doova-709a7.firebaseapp.com',
    databaseURL: 'https://doova-709a7-default-rtdb.firebaseio.com',
    storageBucket: 'doova-709a7.firebasestorage.app',
    measurementId: 'G-61S66N712X',
  );

}